### ISSUE TITLE
Preliminary schedule?

### ISSUE THREAD

**Issue by tadas-s** [euruko/euruko2015.github.io#3]
Hi,

Would it be possible to add preliminary schedule for the conference? By which I mean start/finish hours for both days. Without it I'm not sure if I should book flight back home on Sunday evening or Monday ;)

Cheers

**Comment by bai** [comment]
We're going to add schedule later this week :-) It's going to be 9am—6pm event.

**Comment by tadas-s** [comment]
Cheers :+1:
